content:
  allowed_image_formats:
  - jpg
  - jpeg
  - png
  - gif
  - webp
  include_images: true
  include_menus: false
  include_metadata: true
  max_image_size: 10
  min_content_length: 100
crawling:
  follow_external: false
  max_depth: 5
  max_pages: 1000
  request_delay: 2.0
  respect_robots: false
  timeout: 30
directories:
  logs_dir: logs
  output_dir: output
  temp_dir: temp
cache:
  enabled: true
  directory: cache
  compression: true
  compression_level: 6
  max_sessions: 100
  auto_cleanup: true
  cleanup_settings:
    max_age_days: 30
    keep_completed: 10
  save_frequency: 5
  session_timeout_hours: 24
filters:
  exclude_patterns:
  - .*\.pdf$
  - .*\.zip$
  - .*\.exe$
  - /admin/.*
  - /login.*
  - /logout.*
  max_url_length: 2000
  skip_extensions:
  - pdf
  - zip
  - exe
  - dmg
  - pkg
http:
  max_retries: 3
  retry_delay: 5
  use_cookies: true
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0
human_behavior:
  browsing:
    max_session_pages: 100
    respect_business_hours: false
    robots_respect_probability: 0.8
    session_break_after: 50
    session_break_duration:
    - 30
    - 120
    weekend_factor: 1.2
  delays:
    base_reading_time:
    - 2
    - 8
    complexity_multiplier: 1.5
    fatigue_factor: 0.1
    maximum_delay: 30
    minimum_delay: 0.8
    navigation_decision:
    - 1
    - 3
    variance_percent: 30
  detection_avoidance:
    adaptive_delays: true
    handle_cookies: true
    monitor_rate_limits: true
    realistic_headers: true
    track_referrers: true
logging:
  level: INFO
  log_filename: scraper.log
  log_to_file: true
  rotate_logs: true
markdown:
  include_toc: true
  multi_file: false
  output_filename: scraped_website.md
path_scoping:
  allow_homepage: true
  allow_navigation: limited
  allow_parent_levels: 1
  allow_siblings: true
  enabled: true
  max_external_depth: 1
pdf:
  font:
    family: Arial
    size: 11
  include_page_numbers: true
  include_toc: true
  margins:
    bottom: 20
    left: 15
    right: 15
    top: 20
  output_filename: scraped_website.pdf
  page_size: A4
